REGIONS = {
    'ABCDEFGH': 'Africa',
    'JKLMNPR': 'Asia',
    'STUVWXYZ': 'Europe',
    '12345': 'USA',
    '67': 'Oceania',
    '89': 'South America',
}

WMI = {
    "1F0":("Ford Motor Company (USA)", "FORD", "1F", "USA"),
    "1F1":("Ford Motor Company (USA)", "FORD", "1F", "USA"),
    "1F6":("Detroit Chassis LLC (USA)", "FORD", "1F", "USA"),
    "1F7":("MSX International Detroit, MI", "FORD", "1F", "USA"),
    "1F8":("American Transportation Corp. (USA)", "FORD", "1F", "USA"),
    "1FA":("Ford Motor Company (USA)", "FORD", "1F", "USA"),
    "1FB":("Ford Motor Company (USA)", "FORD", "1F", "USA"),
    "1FC":("Ford Motor Company (USA)", "FORD", "1F", "USA"),
    "1FD":("Ford Motor Company (USA)", "FORD", "1F", "USA"),
    "1FM":("Ford Motor Company (USA)", "FORD", "1F", "USA"),
    "1FT":("Ford Motor Company (USA)", "FORD", "1F", "USA"),
    "1ZV":("Ford Motor Company (USA)", "FORD", "1Z", "USA"),
    "1ZW":("Auto Alliance International (USA)", "FORD", "1Z", "USA"),
    "2FA":("Ford Motor Company of Canada, Ltd. (CAN)", "FORD", "2F", "Canada"),
    "2FD":("Ford Motor Company of Canada, Ltd. (CAN)", "FORD", "2F", "Canada"),
    "2FM":("Ford Motor Company of Canada, Ltd. (CAN)", "FORD", "2F", "Canada"),
    "2FT": ("Ford Motor Company of Canada, Ltd. (CAN)", "FORD", "2F", "Canada"),
    "3FA": ("Ford Motor Company of Canada, Ltd. (CAN)", "FORD", "3F", "Mexico"),
    "3FB": ("Ford Motor Company S.A. (MEX)", "FORD", "3F", "Mexico"),
    "3FC": ("Ford Motor Co SA de CV (MEX)", "FORD", "3F", "Mexico"),
    "3FD": ("Ford Motor Company (Mexico) (MEX)", "FORD", "3F", "Mexico"),
    "3FE": ("Ford Motor Company (Mexico) (MEX)", "FORD", "3F", "Mexico"),
    "3FM": ("Ford Motor Co SA de CV (MEX)", "FORD", "3F", "Mexico"),
    "3FN": ("Blue Diamond Trucks S. De R. L. De C. V. (MEX)", "FORD", "3F", "Mexico"),
    "3FR": ("Blue Diamond Trucks S. De R. L. De C. V. (MEX)", "FORD", "3F", "Mexico"),
    "3FT": ("Ford Motor Company (Mexico) (MEX)", "FORD", "3F", "Mexico"),
    "3LN": ("Ford Motor Co SA de CV (MEX)", "FORD", "3L", "Mexico"),
    "3M9": ("Mopesa Motores Power SA (MEX)", "FORD", "3M", "Mexico"),
    "3MA": ("Ford Motor Co SA de CV (MEX)", "FORD", "3M", "Mexico"),
    "3ME": ("Ford Motor Co SA de CV (MEX)", "FORD", "3M", "Mexico"),
    "6F1": ("Ford Motor Company Australia (AU)", "FORD", "6F", "Australia"),
    "6FP": ("Ford Motor Company Australia (AU)", "FORD", "6F", "Australia"),
    "6FR": ("Ford Motor Co of Australia Ltd (AU)", "FORD", "6F", "Australia"),
    "6FS": ("Ford Motor Co of Australia Ltd (AU)", "FORD", "6F", "Australia"),
    "6FT": ("Ford Motor Co of Australia Ltd (AU)", "FORD", "6F", "Australia"),
    "6MP": ("Ford Motor Co of Australia Ltd (AU)", "FORD", "6M", "Australia"),
    "7A5": ("Ford Motor Company Of New Zealand Ltd (Z)", "FORD", "7A", "New Zealand"),
    "8AF": ("FORD ARGENTINA (ARG)", "FORD", "8In", "Argentina"),
    "8XD": ("Ford Motor de Venezuela SA (V)", "FORD", "8X", "Venezuela"),
    "8YP": ("Ford Motor de Venezuela SA (V)", "FORD", "8Y", "Venezuela"),
    "8YT": ("Ford Motor de Venezuela SA (V)", "FORD", "8Y", "Venezuela"),
    "93R": ("Ford Motor Co Brasil Ltda (BRA)", "FORD", "93", "Brazil"),
    "9BF": ("Ford Motor Company Brasil Ltda. (BRA)", "FORD", "9B", "Brazil"),
    "9BT": ("Ford Motor Company Brasil Ltda. (BRA)", "FORD", "9B", "Brazil"),
    "AFA": ("Samcor (Pty) Ltd (FOR)", "FORD", "OF", "YuAR"),
    "AFM": ("Ford Motor Company of SA (Pty) Ltd (ZA)", "FORD", "OF", "YuAR"),
    "LFA": ("Ford Lio Ho Motor Co Ltd (CHN)", "FORD", "LF", "China"),
    "LFA": ("Ford Lio Ho Motor Co Ltd (CHN)", "FORD", "LF", "Taiwan"),
    "LVS": ("Changan Ford Mazda Motor Company (CHN)", "FORD", "LV", "China"),
    "MAY": ("Ford India Ltd (I)", "FORD", "MA", "India"),
    "MPB": ("Ford Motor Company (Thailand) Limited (THA)", "FORD", "MP", "Thailand"),
    "MS3": ("Ford India Private Limited (I)", "FORD", "MS", "India"),
    "NM0": ("FORD-OTOSAN (TR)", "FORD", "NM", "Turkey"),
    "PE1": ("Ford Motor Co Philippines Inc (PH)", "FORD", "ON", "Philippines"),
    "PE2": ("Ford Motor Co Philippines Inc (PH)", "FORD", "ON", "Philippines"),
    "PE3": ("Ford Motor Co Philippines Inc (PH)", "FORD", "ON", "Philippines"),
    "PE4": ("Ford Motor Co Philippines Inc (PH)", "FORD", "ON", "Philippines"),
    "PR8": ("Ford Malaysia Sdn Bhd (MAL)", "FORD", "PR", "Malaysia"),
    "RHA": ("Ford Lio Ho Motor Co Ltd (T)", "FORD", "RH", "Taiwan"),
    "RHB": ("Ford Lio Ho Motor Co Ltd (T)", "FORD", "RH", "Taiwan"),
    "RL0": ("Ford Vietnam Limited (VIE)", "FORD", "RL", "Vietnam"),
    "RL2": ("Ford Vietnam Limited (VIE)", "FORD", "RL", "Vietnam"),
    "RL3": ("Ford Vietnam Limited (VIE)", "FORD", "RL", "Vietnam"),
    "SBC": ("Iveco Ford Truck Ltd. (UK)", "FORD", "SB", "United Kingdom"),
    "SFA": ("FORD-OTOSAN (TR)", "FORD", "SF", "Turkey"),
    "SFA": ("Ford Motor Company Ltd (GB)", "FORD", "SF", "United Kingdom"),
    "TW2": ("Ford Lutisania sarl (P)", "FORD", "TW", "Portugal"),
    "UN1": ("Henry Ford and Son Ltd (IRL)", "FORD", "A", "Ireland"),
    "VS6": ("Ford Espana its (P)", "FORD", "VS", "Spain"),
    "WF0": ("Ford Werke A.G. (D)", "FORD", "WF", "Germany"),
    "WF0": ("OOO Ford Motor Company (RU)", "FORD", "WF", "Russia"),
    "WF1": ("Ford Werke A.G. (D)", "FORD", "WF", "Germany"),
    "X4F": ("OOO Ford Motor Company (RU)", "FORD", "X4", "Russia"),
    "X9F": ("OOO Ford Motor Company (RU)", "FORD", "X9", "Russia"),
    "XLC": ("Ford Nederland nv (NL)", "FORD", "XL", "Holland"),
    "Y4F": ("Ford Union (BLR)", "FORD", "Y4", "Byelorussia"),
    "YF0": ("Ford-Werke (B)", "FORD", "YF", "Belgium"),
    "Z6F": ("Ford Sollers Holding (RUS)", "FORD", "Z6", "Russia"),
    "ZMJ": ("Ford Italia S.p.A. (I)", "FORD", "ZM", "Italy"),
}

SECURITY_SYSTEMS = {
    "A": "Reel seat belts and air bags for the driver and conventional belts for passenger",
    "B": "Automatic belt",
    "C": "Automatic safety belts and air bags for driver",
    "D": "Automatic belts on front",
    "L": "Automatic belts and airbags for the driver and passengers",
    "P": "Conventional belts front",
    "R": "Conventional belts, front airbag for the driver",
    "S": "Conventional belts, front airbags for driver and passenger",
}

ASSEMBLY_PLANT = {
    "5": "the flat Rock, Michigan, USA",
    "0": "Detroit, Michigan, USA",
    "A": "Hapvill, Georgia, United States",
    "B": "Oakville, Ontario, Canada",
    "C": "Oakville, Ontario, Canada",
    "D": "Eyvon Leyk, Ohio, USA",
    "E": "Louisville Kentucky, USA",
    "F": "Dearborn, Michigan, USA",
    "G": "Chicago, Illinois, USA",
    "H": "Lorraine, Ohio, USA",
    "J": "Monterrey, Mexico",
    "K": "Kansas, Missouri, United States",
    "L": "Wayne, Michigan, United States",
    "M": "Kuatilan, Mexico",
    "N": "Norfolk, Virginia, US",
    "P": "St. Paul, Minnesota, USA",
    "R": "Hermosa Mexico",
    "T": "Edison, New Jersey, USA",
    "U": "Louisville, Kentucky, USA",
    "V": "Escobedo, Mexico",
    "W": "Wayne, Michigan, USA",
    "X": "Saint Thomas, Ontario, Canada",
    "Y": "Vic catfish, Michigan, United States",
    "Z": "Hezelvud, Missouri, USA",
}

MODEL_YEAR_OLD = {
    "A": "1980",
    "B": "1981",
    "C": "1982",
    "D": "1983",
    "E": "1984",
    "F": "1985",
    "G": "1986",
    "H": "1987",
    "J": "1988",
    "K": "1989",
    "L": "1990",
    "M": "1991",
    "N": "1992",
    "P": "1993",
    "R": "1994",
    "S": "1995",
    "T": "1996",
    "V": "1997",
    "W": "1998",
    "X": "1999",
    "Y": "2000",
    "1": "2001",
    "2": "2002",
    "3": "2003",
    "4": "2004",
    "5": "2005",
    "6": "2006",
    "7": "2007",
    "8": "2008",
    "9": "2009",  
}

MODEL_YEAR_NEW = {
    "A": "2010",
    "B": "2011",
    "C": "2012",
    "D": "2013",
    "E": "2014",
    "F": "2015",
    "G": "2016",
    "H": "2017",
    "J": "2018",
    "K": "2019",
    "L": "2020",
    "M": "2021",
    "N": "2022",
    "P": "2023",
    "R": "2024",
    "S": "2025",
    "T": "2026",
    "V": "2027",
    "W": "2028",
    "X": "2029",
    "Y": "2030",
    "1": "2031",
    "2": "2032",
    "3": "2033",
    "4": "2034",
    "5": "2035",
    "6": "2036",
    "7": "2037",
    "8": "2038",
    "9": "2039", 
}

MODEL_3 = {
    "J1C": "Lincoln MKC (J_C - 4x2, J_D - 4x4)",
    "J1D": "Lincoln MKC (J_C - 4x2, J_D - 4x4)",
    "J2C": "Lincoln MKC (J_C - 4x2, J_D - 4x4)",
    "J2D": "Lincoln MKC (J_C - 4x2, J_D - 4x4)",
    "J3C": "Lincoln MKC (J_C - 4x2, J_D - 4x4)",
    "J3D": "Lincoln MKC (J_C - 4x2, J_D - 4x4)",
    "J4C": "Lincoln MKC (J_C - 4x2, J_D - 4x4)",
    "J4D": "Lincoln MKC (J_C - 4x2, J_D - 4x4)",
    "J2H": "Lincoln Navigator",
    "J2J": "Lincoln Navigator",
    "J2K": "Lincoln Navigator",
    "J2L": "Lincoln Navigator",
    "J3H": "Lincoln Navigator",
    "J3J": "Lincoln Navigator",
    "J3K": "Lincoln Navigator",
    "J3L": "Lincoln Navigator",
    "J6J": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J6K": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J6L": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J7J": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J7K": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J7L": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J8J": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J8K": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J8L": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J9J": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J9K": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "J9L": "Lincoln MKX (J6_, J7_ - 4x2, J8_, J9_ - 4x4)",
    "M81": "Lincoln Town Car",
    "M83": "Lincoln Town Car",
    "M84": "Lincoln Town Car",
    "M85": "Lincoln Town Car",
    "M89": "Lincoln Town Car",
    "M86": "Lincoln LS",
    "M87": "Lincoln LS",
    "P3E": "Ford Focus sedan",
    "P3F": "Ford Focus sedan",
    "P3J": "Ford Focus sedan",
    "P3K": "Ford Focus 5dr hatchback",
    "P3L": "Ford Focus 5dr hatchback",
    "P3N": "Ford Focus 5dr hatchback",
    "P3R": "Ford Focus 5dr hatchback",
    "P3T": "Ford Focus RS 5dr hatchback",
    "P4A": "Ford Fiesta sedan",
    "P4B": "Ford Fiesta sedan",
    "P4C": "Ford Fiesta sedan",
    "P4E": "Ford Fiesta 5dr hatchback",
    "P4F": "Ford Fiesta 5dr hatchback",
    "P4G": "Ford Fiesta 5dr hatchback",
    "P4T": "Ford Fiesta 5dr hatchback",
    "P5A": "Ford C-max",
    "P5B": "Ford C-max",
    "P5C": "Ford C-max",
    "P66": 'Ford Contour ("перелицованный" европейский Ford Mondeo)',
    "P68": 'Ford Contour ("перелицованный" европейский Ford Mondeo)',
    "P72": 'Ford Crown Victoria (4-door sedan)',
    "P84": "Mazda6",
    "P8A": "Ford Mustang Coupe",
    "P8C": "Ford Mustang Coupe",
    "P8T": "Ford Mustang Coupe",
    "P8E": "Ford Mustang Convertible",
    "P8F": "Ford Mustang Convertible",
    "P8U": "Ford Mustang Convertible",
}

MODEL_2 = {
    "A5": "Ford Windstar, Ford Freestar",
    "K3": "Ford EDGE FWD",
    "F5": "Stripped motorhome chassis Ford",
    "K4": "Ford EDGE AWD",
    "K7": "Ford Explorer FWD",
    "K8": "Ford Explorer AWD",
    "M5": 'Mercury Sable (a "rich variant" Ford Taurus)',
    "M6": "Mercury Mystique",
    "M7": 'Mercury Grand Marquis (a "rich version of" Ford Crown Victoria)',
    "M9": "Lincoln Continental",
    "P0": "Ford Fusion sedan",
    "P1": "Ford Escort",
    "P3": "Ford Focus",
    "P4": "Ford Mustang",
    "P5": "Ford Taurus",
    "P6": "Ford Thunderbird",
    "P7": "Ford Crown Victoria",
    "P8": "Mazda",
    "P9": "Ford GT",
    "T6": "Mercury Coguar",
    "V1": "Mercury Villager"
}

MODEL_1 = {
    "A": "Minivan",
    "C": "chassis for Ford E-series (Econoline vans and buses)",
    "E": "Ford E-series (Econoline vans and buses)",
    "M": "cars brands Mercury and Lincoln",
    "R": "Pick-up Ford Ranger",
    "S": "Ford E-series (Econoline vans and buses) on the elongated chassis (extended)",
    "W": "Ford F-Series crew cab",
    "X": "Ford F-Series super cab"
}